"""
Django settings for foodorder project.
Generated by 'django-admin startproject' using Django 5.2.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import pymysql

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pz51z+sd!)io%#^!6c*%xg1673f6p0-pe95@e(1^rc%t8(eu$w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',       
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'main',
    'users',
    'menu',
    'cart',
    'orders',
    'payments',
    'admin_panel',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.FrontendAuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'users.backends.FrontendUserBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'foodorder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'foodorder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'FOS',   
        'USER': 'root',            
        'PASSWORD': '',            
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# If you have custom static folder, add this to find your logo image
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'


SESSION_COOKIE_NAME = 'frontend_sessionid'

# Authentication settings
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# eSewa Integration (Test Mode)
ESEWA_FORM_URL = 'https://rc-epay.esewa.com.np/api/epay/main/v2/form'
ESEWA_VERIFY_URL = 'https://rc.esewa.com.np/api/epay/transaction'
ESEWA_MERCHANT_CODE = 'EPAYTEST'  


pymysql.install_as_MySQLdb()


JAZZMIN_SETTINGS = {
    "site_title": "FOS Admin",
    "site_header": "Food Ordering System",
    "site_brand": "FOS Admin",
    "welcome_sign": "Welcome to the FOS Admin Panel",
    "copyright": "FOS 2025",
    "search_model": ["menu.FoodItem", "orders.Order"],

    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "menu"},
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "menu.FoodItem": "fas fa-hamburger",
        "orders.Order": "fas fa-receipt",
    },

    "show_sidebar": True,
    "navigation_expanded": True,

    "dashboard_cards": [
        {
            "type": "model",
            "model": "auth.user",
            "label": "Users",
            "description": "Total registered users",
            "order": 1,
        },
        {
            "type": "model",
            "model": "menu.fooditem",
            "label": "Food Items",
            "description": "All food items available",
            "order": 2,
        },
        {
            "type": "model",
            "model": "menu.category",
            "label": "Categories",
            "description": "Food categories",
            "order": 3,
        },
        {
            "type": "link",
            "url": "/admin/orders/order/",
            "label": "Orders",
            "description": "View all orders",
            "order": 4,
        },
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
      
        "menu": "fas fa-utensils",
        "orders": "fas fa-shopping-cart",
        "cart": "fas fa-shopping-basket",
        "payments": "fas fa-credit-card",
        "users": "fas fa-users",
        
    
        "menu.FoodItem": "fas fa-hamburger",
        "menu.Category": "fas fa-tags",
        "orders.Order": "fas fa-receipt",
    },

    "site_logo": "images/logoo.png",

    "theme": "dark",  
    "navbar_bg": "f15a24",
    "navbar_text": "ffffff",
    "sidebar_bg": "23272a",
    "sidebar_hover_bg": "f15a24",
    "sidebar_active_bg": "e04e1b",
    "sidebar_active_text": "ffffff",
    "topmenu_bg": "f15a24",
    "topmenu_hover_bg": "e04e1b",
    "site_bg": "2c2f33",
    "site_text_color": "ffffff",


     "custom_css": "css/custom_admin.css", 
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}


LOGIN_URL = 'login'
